name: Challenge1

on:
  workflow_dispatch:

jobs:
  job1:
    name: Initial Setup
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          echo "Current Date:"
          date
          echo "Working Directory:"
          pwd
          echo "Directory Contents:"
          ls -la
